using ModForge.Shared.Models.Enums;
using System.Globalization;

namespace ModForge.Shared.Models.Attributes
{
	public static class BuffParamSerializer
	{
		private static readonly Dictionary<MathOperation, string> OperatorMap = new()
		{
			{ MathOperation.AddAbsolute, "+" },
			{ MathOperation.SubtractAbsolute, "-" },
			{ MathOperation.SetAbsolute, "=" },
			{ MathOperation.AddRelativeToBase, "*" },
			{ MathOperation.MultiplyCurrent, "%" },
			{ MathOperation.Minimum, "<" },
			{ MathOperation.Maximum, ">" },
			{ MathOperation.NegateRelativeToValue, "!" }
		};

		private static readonly Dictionary<string, Dictionary<string, string>> buffParamMap = new()
		{
			{ "strength", new() { { "Stat Strength", "Affects the character's physical power, influencing melee damage and the ability to carry heavy equipment." } } },
			{ "agility", new() { { "Stat Agility", "Determines the character's speed, reflexes, and effectiveness with ranged weapons or dodging." } } },
			{ "vitality", new() { { "Stat Vitality", "Represents physical resilience, influencing health regeneration and endurance." } } },
			{ "speech", new() { { "Stat Speech", "Affects persuasion in dialogues, trading outcomes, and social interactions." } } },
			{ "vision", new() { { "Stat Vision", "Modifies how well the character can see, especially in darkness or at distance." } } },
			{ "hearing", new() { { "Stat Hearing", "Determines how well the character can detect sounds, such as approaching enemies or environmental cues." } } },
			{ "barter", new() { { "Stat Barter", "Influences the effectiveness of trading, affecting prices when buying or selling goods." } } },
			{ "courage", new() { { "Stat Courage", "Reflects the character's bravery, possibly affecting resistance to fear or fleeing behavior." } } },
			{ "storyProgress", new() { { "Stat Story Progress", "Tracks the advancement through the main storyline and major quest milestones." } } },
			{ "prestige", new() { { "Stat Prestige", "Represents the character's reputation and standing within the world, possibly influencing NPC reactions." } } },
			{ "stealth", new() { { "Skill Stealth", "Determines how effectively the player can move undetected, sneak past enemies, and perform stealth actions." } } },
			{ "horse_riding", new() { { "Skill Horse Riding", "Improves control and performance while riding a horse, affecting speed, maneuverability, and mounted combat." } } },
			{ "fencing", new() { { "Skill Fencing", "Measures skill with one-handed bladed weapons, such as sabres or rapiers." } } },
			{ "bard", new() { { "Skill Bard", "Enhances social and entertainment abilities, possibly affecting speech, persuasion, and interactions in taverns or court." } } },
			{ "thievery", new() { { "Skill Thievery", "Affects the ability to steal, pick locks, and avoid detection while committing crimes." } } },
			{ "pickpocketing_obsolete", new() { { "Skill Pickpocketing Obsolete", "An outdated or deprecated value once related to stealing items directly from NPCs." } } },
			{ "alchemy", new() { { "Skill Alchemy", "Improves potion brewing and the identification of alchemical ingredients and effects." } } },
			{ "cooking", new() { { "Skill Cooking", "Determines the player's ability to prepare meals that restore health or provide temporary buffs." } } },
			{ "craftsmanship", new() { { "Skill Craftsmanship", "General skill for crafting various items, potentially covering tailoring, leatherwork, or construction." } } },
			{ "smithing_obsolete", new() { { "Skill Smithing Obsolete", "A deprecated skill related to forging or repairing weapons and armor." } } },
			{ "fishing", new() { { "Skill Fishing", "Improves success at catching fish, possibly affecting yield and quality." } } },
			{ "mining", new() { { "Skill Mining", "Determines how efficiently the player can extract ores or materials from mines." } } },
			{ "first_aid", new() { { "Skill First Aid", "Affects the ability to treat injuries, heal wounds, or stabilize characters in critical condition." } } },
			{ "drinking", new() { { "Skill Drinking", "Represents alcohol tolerance and related perks, possibly reducing negative effects of intoxication." } } },
			{ "survival", new() { { "Skill Survival", "General wilderness knowledge, such as tracking, gathering herbs, or navigating terrain." } } },
			{ "defense", new() { { "Skill Defense", "Influences blocking, parrying, and overall resistance during combat." } } },
			{ "weapon_sword", new() { { "Skill Weapon Sword", "Determines effectiveness when using swords in combat, including damage and combos." } } },
			{ "heavy_weapons", new() { { "Skill Heavy Weapons", "Represents proficiency with large, heavy weapons such as axes or maces." } } },
			{ "weapon_bow_obsolete", new() { { "Skill Weapon Bow Obsolete", "A deprecated skill value once associated with archery." } } },
			{ "marksmanship", new() { { "Skill Marksmanship", "Measures precision and effectiveness with ranged weapons, especially bows and crossbows." } } },
			{ "weapon_shield", new() { { "Skill Weapon Shield", "Determines proficiency with shields, affecting blocking efficiency and stamina use in defense." } } },
			{ "weapon_mace_obsolete", new() { { "Skill Weapon Mace Obsolete", "A deprecated value once used to represent skill with blunt weapons such as maces." } } },
			{ "weapon_dagger", new() { { "Skill Weapon Dagger", "Measures effectiveness in combat using daggers, including quick attacks and stealth kills." } } },
			{ "weapon_large", new() { { "Skill Weapon Large", "Represents the player's skill with two-handed or oversized weapons like greatswords or polearms." } } },
			{ "weapon_unarmed", new() { { "Skill Weapon Unarmed", "Affects damage and effectiveness in hand-to-hand combat without weapons." } } },
			{ "herbalism_obsolete", new() { { "Skill Herbalism Obsolete", "An outdated skill once related to harvesting herbs and preparing natural remedies." } } },
			{ "scholarship", new() { { "Skill Scholarship", "Reflects knowledge of reading, writing, and scholarly pursuits such as history or theology." } } },
			{ "tailoring", new() { { "Skill Tailoring", "Enables crafting and repairing of clothing and light armor." } } },
			{ "armourer", new() { { "Skill Armourer", "Affects the ability to craft, maintain, or enhance armor pieces." } } },
			{ "weaponsmithing", new() { { "Skill Weaponsmithing", "Determines proficiency in forging and improving weapons." } } },
			{ "shoemaking", new() { { "Skill Shoemaking", "Covers crafting and repairing footwear, possibly affecting movement and stealth bonuses." } } },
			{ "gunsmithing", new() { { "Skill Gunsmithing", "Relates to maintenance and crafting of firearms, if present in the game." } } },
			{ "bowyery", new() { { "Skill Bowyery", "Involves the crafting and tuning of bows for better performance in ranged combat." } } },
			{ "gambling", new() { { "Skill Gambling", "Affects outcomes in games of chance, including dice or betting interactions." } } },
			{ "houndmaster", new() { { "Skill Houndmaster", "Reflects ability to command, train, and use dogs in hunting or combat situations." } } },
			{ "health", new() { { "S State Health", "Represents the character's overall vitality; when it reaches zero, the player dies." } } },
			{ "stamina", new() { { "S State Stamina", "Determines how long the player can perform physical actions like running, fighting, or blocking before becoming fatigued." } } },
			{ "exhaust", new() { { "S State Exhaust", "Indicates how tired the character is, possibly affecting movement, perception, or combat performance." } } },
			{ "hunger", new() { { "S State Hunger", "Tracks the need for food; high hunger levels reduce performance or lead to penalties." } } },
			{ "karma", new() { { "S State Karma", "Reflects the moral alignment of the character's actions, potentially influencing how NPCs react or whether certain options are available." } } },
			{ "alcoholism", new() { { "S State Alcoholism", "Represents the player's dependence on alcohol; may cause withdrawal effects or penalties when sober." } } },
			{ "ade", new() { { "Inter Armor Defense", "Affects the defensive value provided by armor, reducing incoming physical damage." } } },
			{ "uat", new() { { "Inter Unarmed Attack", "Determines the strength or effectiveness of unarmed strikes in combat." } } },
			{ "wat", new() { { "Inter Weapon Attack", "Influences the damage output of weapon-based attacks." } } },
			{ "wac", new() { { "Inter Weapon Attack Cost", "Represents how much stamina is consumed when performing a weapon attack." } } },
			{ "ahm", new() { { "Inter Attack From Horse Mod", "Modifies effectiveness or damage of attacks performed while mounted on horseback." } } },
			{ "rtm", new() { { "Inter Rider Threats To Horse Morale", "Affects how enemy presence or actions impact the morale or behavior of the player's horse." } } },
			{ "act", new() { { "Inter Movement Proficiency", "Indicates how efficiently the character moves, potentially reducing stamina cost or increasing speed." } } },
			{ "asp", new() { { "Inter Attack Speed 01", "Determines how quickly the player can perform attacks in combat." } } },
			{ "pbs", new() { { "Inter Perfect Block Slot 01", "Increases the window of opportunity for executing a perfect block." } } },
			{ "cli", new() { { "Inter Clinch Advantage", "Affects success in clinch situations, determining dominance during close combat grapples." } } },
			{ "hlh", new() { { "Inter Health Loss Hit", "Modifies the amount of health lost when taking a hit." } } },
			{ "slh", new() { { "Inter Stamina Loss Hit", "Determines how much stamina is lost when receiving an enemy attack." } } },
			{ "sls", new() { { "Inter Stamina Loss Blocking Shield", "Represents the stamina cost of blocking attacks with a shield." } } },
			{ "dig", new() { { "Inter Digestion Speed", "Affects how quickly consumed food is digested, impacting hunger and stamina over time." } } },
			{ "exh", new() { { "Inter Exhaustion Speed", "Determines how rapidly exhaustion accumulates during physical activities." } } },
			{ "hod", new() { { "Inter Hangover Duration", "Modifies how long negative effects from alcohol last after sobering up." } } },
			{ "psp", new() { { "Inter Potion Heal Speed", "Affects the speed at which health potions take effect." } } },
			{ "lcs", new() { { "Inter Lock Cursor Shake", "Controls how much the cursor shakes while lockpicking, impacting difficulty." } } },
			{ "srg", new() { { "Inter Stamina Regen", "Determines how quickly stamina regenerates over time." } } },
			{ "sco", new() { { "Inter Stamina Consumption", "Represents the general stamina cost of actions like attacking or running." } } },
			{ "srb", new() { { "Inter Stamina Regen Block", "Modifies stamina regeneration while blocking attacks." } } },
			{ "sra", new() { { "Inter Stamina Regen Attack", "Affects how quickly stamina regenerates after executing an attack." } } },
			{ "ard", new() { { "Inter Archery Stamina Drain", "Modifies how much stamina is drained while aiming or drawing a bow." } } },
			{ "skp", new() { { "Inter Stealth Kill Probability", "Determines the likelihood of successfully performing a stealth kill without being detected." } } },
			{ "rst", new() { { "Inter Relative Stamina Max", "Modifies the character’s maximum stamina relative to their base value." } } },
			{ "pdp", new() { { "Inter Pull Down Probability", "Represents the chance of successfully pulling an enemy to the ground during a grappling move." } } },
			{ "eep", new() { { "Inter Random Event Escape Probability", "Influences the likelihood of escaping from hostile encounters or random world events." } } },
			{ "lpd", new() { { "Inter Lockpicking Difficulty", "Adjusts the complexity of lockpicking interactions, making them easier or harder." } } },
			{ "lpn", new() { { "Inter Lockpicking Noise Multiplier", "Modifies the amount of noise generated while lockpicking, affecting the chance of being heard." } } },
			{ "ain", new() { { "Inter Attack Injury", "Determines the chance or severity of injuries caused to opponents during attacks." } } },
			{ "hin", new() { { "Inter Hit Injury", "Represents how likely the player is to suffer injuries when hit." } } },
			{ "fae", new() { { "Inter First Aid Efficiency", "Affects how effectively first aid heals or stabilizes the player." } } },
			{ "dee", new() { { "Inter Damage To Enemy Armor", "Modifies the amount of damage dealt to an opponent’s armor." } } },
			{ "dew", new() { { "Inter Damage To Enemy Weapon", "Affects the durability loss of an enemy’s weapon when struck or parried." } } },
			{ "osb", new() { { "Inter Opponent Stamina Loss Blocking", "Represents the stamina loss incurred by enemies when their attacks are blocked." } } },
			{ "dsl", new() { { "Inter Dodge Slot", "Increases the window or effectiveness of performing a dodge maneuver." } } },
			{ "cos", new() { { "Inter Combo Slot 01", "Expands the number or timing of available combo attacks." } } },
			{ "pac", new() { { "Inter Weapon Poison Apply Chance", "Determines how likely poison is to be applied to a weapon strike." } } },
			{ "lpb", new() { { "Inter Lockpicking Lockpick Break Chance", "Modifies the chance that a lockpick will break during lockpicking." } } },
			{ "res", new() { { "Inter Recognition Speed", "Affects how quickly NPCs recognize or identify the player." } } },
			{ "ors", new() { { "Inter Observer Recognition Speed", "Modifies how fast other characters (observers) notice the player’s actions or presence." } } },
			{ "ptp", new() { { "Inter Pickpocketing Time Penalty", "Adds or reduces penalty time when pickpocketing, impacting success chance." } } },
			{ "shr", new() { { "Inter Sleep Health Regen Modifier", "Changes how much health is restored during sleep." } } },
			{ "ser", new() { { "Inter Sleep Exhaust Regen Modifier", "Determines how much exhaustion is recovered while sleeping." } } },
			{ "pim", new() { { "Inter Poison Immunity", "Indicates resistance or immunity to poison effects." } } },
			{ "ald", new() { { "Inter Alcoholism Debuff Modifier", "Adjusts the severity of penalties from alcoholism, such as reduced stats or blurred vision." } } },
			{ "aam", new() { { "Inter Alcohol Absorbtion", "Determines how quickly alcohol is absorbed, affecting how fast intoxication sets in." } } },
			{ "uab", new() { { "Inter Unawared Victim Attack Bonus Mod", "Provides a damage or success bonus when attacking unaware or unsuspecting enemies." } } },
			{ "fhm", new() { { "Inter Food Health Modifier", "Influences how food affects health, potentially boosting or reducing its healing effect." } } },
			{ "fne", new() { { "Inter Fine", "Represents monetary penalties applied to the player for crimes or violations." } } },
			{ "dth", new() { { "Inter Damage To Heart", "Indicates damage dealt to the heart, which may cause severe health loss or fatal conditions." } } },
			{ "dtd", new() { { "Inter Damage To Head", "Affects how much damage is delivered to the head area during combat." } } },
			{ "tdh", new() { { "Inter Taken Damage To Head", "Modifies the damage the player receives when struck on the head." } } },
			{ "adc", new() { { "Inter Aditional Dog Clinch Mod", "Provides a modifier to dog-assisted clinch actions, improving their effectiveness." } } },
			{ "sla", new() { { "Inter Slash Attack", "Modifies damage or effectiveness of slashing attacks with edged weapons." } } },
			{ "sta", new() { { "Inter Stab Attack", "Modifies damage or effectiveness of stabbing attacks with pointed weapons." } } },
			{ "ssa", new() { { "Inter Smash Attack", "Affects the power or impact of blunt or smashing attacks." } } },
			{ "wsr", new() { { "Inter Weapon Strength Requirement", "Sets the strength required to effectively wield a weapon." } } },
			{ "war", new() { { "Inter Weapon Agility Requirement", "Sets the agility required to effectively wield a weapon." } } },
			{ "wrs", new() { { "Inter Weapon Requirement Strength Stat", "Links weapon usability to the player's strength attribute." } } },
			{ "wra", new() { { "Inter Weapon Requirement Agility Stat", "Links weapon usability to the player's agility attribute." } } },
			{ "efc", new() { { "Inter Event Flee Chance", "Determines the likelihood of successfully fleeing from scripted or random events." } } },
			{ "dsc", new() { { "Inter Dodge Stamina Cost", "Modifies how much stamina is consumed when performing a dodge." } } },
			{ "wde", new() { { "Inter Weapon Defense", "Represents the weapon’s defensive capability when used to block or parry." } } },
			{ "ewd", new() { { "Inter Enemy Weapon Defense", "Indicates how well enemy weapons perform in defense, impacting parry and block success." } } },
			{ "scv", new() { { "Inter Skill Check Skill Value", "Determines the skill value used when performing a skill check." } } },
			{ "scx", new() { { "Inter Skill Check Skill XP", "Modifies how much experience is gained from successful skill checks." } } },
			{ "cat", new() { { "Inter Clinch Attack", "Affects effectiveness or damage of attacks initiated from a clinch." } } },
			{ "acm", new() { { "Inter Attack Charging Mod", "Modifies the effect of charging an attack before release, potentially increasing damage." } } },
			{ "rat", new() { { "Inter Ranged Weapon Attack", "Determines effectiveness or damage of attacks using ranged weapons like bows or crossbows." } } },
			{ "rls", new() { { "Inter Reload Speed", "Determines how quickly ranged weapons can be reloaded." } } },
			{ "ptw", new() { { "Inter Player Time Warp", "Modifies the player’s perception of time flow, potentially speeding up or slowing down actions." } } },
			{ "ala", new() { { "Inter Alchemy Potion Amount", "Affects the quantity of potion produced in alchemy crafting." } } },
			{ "apq", new() { { "Inter Alchemy Potion Quality", "Determines the quality level of potions created through alchemy, influencing their effectiveness." } } },
			{ "bid", new() { { "Inter Blocking Item Damage", "Modifies damage taken by items used for blocking, affecting their durability loss." } } },
			{ "fob", new() { { "Inter Finticka Opponent Block Probability", "Influences the chance that an opponent will successfully block a finticka (feint) attack." } } },
			{ "ode", new() { { "Inter Opponent Armor Defense", "Represents how much damage the opponent’s armor can absorb or reduce." } } },
			{ "dmd", new() { { "Inter Dog Morale Decay By Time", "Controls how quickly a dog’s morale decreases over time when inactive or not fed." } } },
			{ "dmh", new() { { "Inter Dog Morale Decay By Hit", "Determines how much a dog’s morale decreases when it is hit or takes damage." } } },
			{ "drn", new() { { "Inter Dog Return Time", "Specifies the time it takes for a dog to return to the player after being called or released." } } },
			{ "bqc", new() { { "Inter Bed Quality Clamped", "Represents the effective bed quality, limited to a maximum value for sleep benefits." } } },
			{ "bqy", new() { { "Inter Bed Quality", "Determines the overall quality of a bed, affecting sleep regeneration and comfort." } } },
			{ "ifc", new() { { "Inter Item Fade Coef", "Controls how quickly items visually fade or degrade in appearance over time." } } },
			{ "pwc", new() { { "Inter Poison Weapon Charge Count", "Indicates how many charges of poison can be applied to a weapon before depletion." } } },
			{ "paa", new() { { "Inter Poison Ammo Apply Count", "Determines how many ammo rounds can be coated with poison before reapplication is needed." } } },
			{ "itd", new() { { "Inter Item Decay", "Modifies the rate at which items deteriorate or lose durability." } } },
			{ "rkm", new() { { "Inter Repair Kit Repair Price Modifier", "Adjusts the cost effectiveness of repair kits used on items or equipment." } } },
			{ "rhm", new() { { "Inter Forced Horse Rear Moral Hit Multiplier", "Modifies the impact of morale damage to horses when they rear or are startled." } } },
			{ "phv", new() { { "Inter Potion Heal Value", "Determines how much health is restored by consuming potions." } } },
			{ "bnv", new() { { "Inter Beer Nutrition Value", "Represents the nutritional value provided by consuming beer." } } },
			{ "pnv", new() { { "Inter Potion Nutrition Value", "Indicates the nutrition gained from consuming potions." } } },
			{ "fnv", new() { { "Inter Food Nutrition Value", "Represents the nutritional content of food items." } } },
			{ "aps", new() { { "Inter Ammo Projectile Speed", "Determines the flight speed of ammunition projectiles like arrows or bolts." } } },
			{ "fbm", new() { { "Inter Foot Step In Bushes Multiplier", "Modifies the noise or detection chance when stepping through bushes or foliage." } } },
			{ "tdm", new() { { "Inter Timed Delta Multiplier", "Affects time-based multipliers for buffs or debuffs, adjusting their duration or strength over time." } } },
			{ "cps", new() { { "Inter Inventory Capacity Per Strength", "Increases inventory carrying capacity based on the player’s strength stat." } } },
			{ "spv", new() { { "Inter Stamina Per Vitality", "Modifies stamina regeneration or maximum stamina based on vitality attribute." } } },
			{ "pct", new() { { "Inter Pickpocketing Charge Time Ratio", "Alters the time required to prepare or charge a pickpocket attempt." } } },
			{ "nhp", new() { { "Inter Non Healing Potion Digestion Speed", "Determines how quickly non-healing potions are metabolized and leave the system." } } },
			{ "nrb", new() { { "Inter Nervousness For Recognition Border", "Represents the nervousness threshold affecting NPC recognition or suspicion of the player." } } },
			{ "btd", new() { { "Inter Blood Transfer From Damage", "Indicates how much blood is lost or transferred due to damage taken." } } },
			{ "charisma", new() { { "Deriv Stat Charisma", "Represents the character’s charm and social influence in interactions." } } },
			{ "rch", new() { { "Deriv Stat Relative Charisma", "Measures charisma relative to other characters, influencing social dynamics." } } },
			{ "cse", new() { { "Deriv Stat Charisma Strength Effect", "Modifies the effect of charisma based on character’s physical strength." } } },
			{ "vib", new() { { "Deriv Stat Visibility", "Determines how visible the character is to NPCs or enemies." } } },
			{ "evi", new() { { "Deriv Stat Equip Visibility", "Measures the visibility impact of equipped items on the character." } } },
			{ "con", new() { { "Deriv Stat Conspicuousness", "Indicates how conspicuous or noticeable the character is in their environment." } } },
			{ "mst", new() { { "Deriv Stat Max Stamina", "The maximum stamina pool the character can have." } } },
			{ "mhs", new() { { "Deriv Stat Max Healthy Stamina", "Maximum stamina available when the character is in healthy condition." } } },
			{ "hlt", new() { { "Deriv Stat Healthiness", "Represents the overall health state of the character." } } },
			{ "sdt", new() { { "Deriv Stat Stamina Derivation", "Calculation or source determining stamina values." } } },
			{ "fov", new() { { "Deriv Stat Field Of View", "The angle or range of vision the character can perceive." } } },
			{ "vir", new() { { "Deriv Stat View Radius", "The radius or distance the character can see or detect objects." } } },
			{ "tsr", new() { { "Deriv Stat Target Search Radius", "Defines how far the character can search for targets or interactables." } } },
			{ "dtf", new() { { "Deriv Stat Dice Throw Fixing", "Modifies dice roll results to affect randomness in favor of the player." } } },
			{ "dbf", new() { { "Deriv Stat Dice Bust Fixing", "Adjusts the chance to avoid a critical failure on dice rolls." } } },
			{ "pt1", new() { { "Deriv Stat Perfect Throw Multiplier 1", "Multiplier applied for perfect dice throw with one success." } } },
			{ "pt5", new() { { "Deriv Stat Perfect Throw Multiplier 5", "Multiplier applied for perfect dice throw with five successes." } } },
			{ "dai", new() { { "Deriv Stat Dice AI Difficulty", "Adjusts AI difficulty related to dice games or chances." } } },
			{ "bnc", new() { { "Deriv Stat Dice Badge No Consumption Probability", "Probability that dice badges are not consumed after use." } } },
			{ "hac", new() { { "Deriv Stat Haggle Additional Chances", "Increases additional chances for successful haggling or trading." } } },
			{ "hde", new() { { "Deriv Stat Haggle Denial", "Reduces chances of haggling failures or denials." } } },
			{ "lfu", new() { { "Deriv Stat Lock Fail Unlock Probability", "Chance to unlock a lock after a failed attempt." } } },
			{ "lio", new() { { "Deriv Stat Lock Instant Open Difficulty", "Difficulty of opening a lock instantly without tools." } } },
			{ "cap", new() { { "Deriv Stat Inventory Capacity", "Maximum carrying capacity of the character's inventory." } } },
			{ "alo", new() { { "Deriv Stat Armor Load", "Total weight or burden of armor worn by the character." } } },
			{ "oad", new() { { "Deriv Stat Overall Armor Defense", "Cumulative defensive value provided by all worn armor." } } },
			{ "owa", new() { { "Deriv Stat Overall Weapon Attack", "Total offensive power from all weapons equipped." } } },
			{ "wud", new() { { "Deriv Stat Weapon Usage Damage Modifier", "Modifies damage caused by weapon usage over time or wear." } } },
			{ "lvl", new() { { "Deriv Stat Main Level", "The character's main progression or level value." } } },
			{ "noi", new() { { "Deriv Stat Noise", "Amount of noise generated by the character, influencing stealth." } } },
			{ "fsm", new() { { "Deriv Stat Footstep Sound Multiplier", "Multiplier affecting the loudness of footsteps." } } },
			{ "nrs", new() { { "Deriv Stat Normalized Run Speed", "The character’s normalized running speed factoring all modifiers." } } },
			{ "rsb", new() { { "Deriv Stat Run Speed Base", "The base running speed before any modifiers or effects are applied." } } },
			{ "nsb", new() { { "Deriv Stat Normalized Run Speed Base", "Normalized base run speed used for calculations to balance speed values." } } },
			{ "rsa", new() { { "Deriv Stat Relative Movement Speed Addition", "Additional movement speed modifier relative to base speed." } } },
			{ "ble", new() { { "Deriv Stat Bleeding Total", "Represents the total bleeding damage affecting the character." } } },
			{ "ibi", new() { { "Deriv Stat Injury Bleeding Interval", "The interval or frequency at which bleeding damage is applied." } } },
			{ "bow", new() { { "Deriv Stat Body Weight", "The overall weight of the character’s body affecting stamina and movement." } } },
			{ "cow", new() { { "Deriv Stat Collision Weight", "Weight used in collision physics impacting knockbacks and pushes." } } },
			{ "aco", new() { { "Deriv Stat Armor Collision Weight", "Collision weight specifically contributed by worn armor." } } },
			{ "caw", new() { { "Deriv Stat Carried Weight", "Total weight of all items currently carried by the character." } } },
			{ "rcw", new() { { "Deriv Stat Relative Carried Weight", "Carried weight relative to the character's carrying capacity." } } },
			{ "mor", new() { { "Deriv Stat Morale", "Current morale level influencing combat effectiveness and behavior." } } },
			{ "dem", new() { { "Deriv Stat Default Morale", "Baseline morale value used in the absence of modifiers." } } },
			{ "mcf", new() { { "Deriv Stat Morale Context Fading Modifier", "Rate at which morale effects fade over time depending on context." } } },
			{ "obe", new() { { "Deriv Stat Obedience", "Measure of how obedient or compliant the character is to commands or authority." } } },
			{ "psr", new() { { "Deriv Stat POI Search Radius", "Radius within which the character can detect Points Of Interest." } } },
			{ "xpm", new() { { "Deriv Stat XP Multiplier", "Multiplier that affects the amount of experience points gained." } } },
			{ "osl", new() { { "Deriv Stat Oversleepness", "Degree to which the character is oversleeping affecting wakefulness." } } },
			{ "mos", new() { { "Deriv Stat Max Oversleepness", "Maximum allowable oversleepness before penalties apply." } } },
			{ "ore", new() { { "Deriv Stat Overreadness", "Level of mental fatigue due to excessive reading or focus." } } },
			{ "caf", new() { { "Deriv Stat Caffeine", "Amount of caffeine in the character’s system affecting alertness." } } },
			{ "rdq", new() { { "Deriv Stat Reading Quality", "Quality metric representing effectiveness of reading activities." } } },
			{ "erq", new() { { "Deriv Stat Effective Reading Quality", "Actual impact of reading quality after modifiers." } } },
			{ "sle", new() { { "Deriv Stat Sleeping", "Current sleep state or duration influencing recovery." } } },
			{ "coc", new() { { "Deriv Stat Consciousness", "Level of awareness and alertness of the character." } } },
			{ "ufo", new() { { "Deriv Stat Unconsciousness Fadeout Speed", "Speed at which unconsciousness effects diminish." } } },
			{ "mut", new() { { "Deriv Stat Mute", "Status indicating whether the character is unable to speak." } } },
			{ "prb", new() { { "Deriv Stat Perception Priority Boost", "Modifier that increases the priority of perception checks." } } },
			{ "fpa", new() { { "Deriv Stat Food Poisoning Antidote", "Effectiveness of antidotes against food poisoning." } } },
			{ "apa", new() { { "Deriv Stat Alcohol Poisoning Antidote", "Effectiveness of antidotes against alcohol poisoning." } } },
			{ "cag", new() { { "Deriv Stat Combat Aggression", "Determines how aggressively the character behaves during combat situations." } } },
			{ "def", new() { { "Deriv Stat Defensiveness", "Measures the tendency of the character to prioritize defense in combat." } } },
			{ "dru", new() { { "Deriv Stat Drunkenness", "Level of intoxication affecting character behavior and abilities." } } },
			{ "poi", new() { { "Deriv Stat Poisoning", "Degree to which the character is affected by poison." } } },
			{ "pos", new() { { "Deriv Stat Pocket Sight", "Ability to notice and detect pickpocketing or similar sneaky actions." } } },
			{ "ran", new() { { "Deriv Stat Robbed Angriness", "Level of anger or aggression after being robbed." } } },
			{ "iex", new() { { "Deriv Stat Item Expert", "Skill or knowledge level related to items, influencing their use or value." } } },
			{ "hcm", new() { { "Deriv Stat Horse Courage Mod", "Modifier affecting a horse's bravery in dangerous or combat situations." } } },
			{ "was", new() { { "Deriv Stat Ranged Weapon Aim Spread", "Spread or accuracy of ranged weapon aiming." } } },
			{ "grm", new() { { "Deriv Stat Good Reputation Mod", "Modifier reflecting positive reputation impacts on the character." } } },
			{ "brm", new() { { "Deriv Stat Bad Reputation Mod", "Modifier reflecting negative reputation impacts on the character." } } },
			{ "drt", new() { { "Deriv Stat Dirtiness", "Degree of how dirty or unclean the character is, affecting perception and possibly interactions." } } },
			{ "sml", new() { { "Deriv Stat Smell", "Overall smell signature of the character, affecting stealth and detection." } } },
			{ "smi", new() { { "Deriv Stat Smell Intensity", "Intensity or strength of the character's smell." } } },
			{ "frg", new() { { "Deriv Stat Fragrance", "Pleasant scent level that might influence NPC reactions." } } },
			{ "hko", new() { { "Deriv Stat Head Hit Knock Out Probability", "Chance of being knocked out when hit in the head." } } },
			{ "enc", new() { { "Deriv Stat Encumberance", "The load the character is carrying relative to their carrying capacity, affecting movement and stamina." } } },
			{ "fdm", new() { { "Deriv Stat Fall Damage Multiplier", "Multiplier affecting the damage taken from falls." } } },
			{ "sma", new() { { "Deriv Stat Sell Margin Adjust", "Adjustment to profit margins when selling items." } } },
			{ "bma", new() { { "Deriv Stat Buy Margin Adjust", "Adjustment to cost margins when buying items." } } },
			{ "hgs", new() { { "Deriv Stat Herb Gather Strength XP", "Experience gained from gathering herbs, influenced by this stat." } } },
			{ "pds", new() { { "Deriv Stat Picklock Damage Speed", "Speed at which picklocks are damaged during lockpicking attempts." } } },
			{ "sha", new() { { "Deriv Stat Bow Self Harm Attack", "Chance or amount of self-inflicted damage when using a bow improperly." } } },
			{ "pbm", new() { { "Deriv Stat Crafted Potions Buy Margin Adjust", "Adjustment to buying margins specifically for crafted potions." } } },
			{ "rml", new() { { "Deriv Stat Random Money Loot", "Amount or chance of random money found as loot." } } },
			{ "hml", new() { { "Deriv Stat Horse Throw Down Morale Limit", "Morale threshold that influences if a horse throws its rider." } } },
			{ "bso", new() { { "Deriv Stat Basket Suspiciency Mod", "Modifier related to basket carrying capacity or stability." } } },
			{ "bld", new() { { "Deriv Stat Bloodiness", "Level of blood or gore on the character, potentially affecting NPC reactions." } } },
			{ "bba", new() { { "Deriv Stat Body Base Armor", "Base armor value provided by the character's body, excluding worn armor." } } },
			{ "arr", new() { { "Deriv Stat Armor Rating", "Overall rating of the character’s armor effectiveness." } } },
			{ "jrm", new() { { "Deriv Stat Jail Recovery Speed Mod", "Modifier affecting the speed at which the character recovers from jail." } } },
			{ "sur", new() { { "Deriv Stat Surrendering", "Indicates the tendency of the character to surrender in combat." } } },
			{ "imm", new() { { "Deriv Stat Immortality", "Determines if the character is immune to damage or death." } } },
			{ "apr", new() { { "Deriv Stat Attack Protection", "Amount of protection the character has against attacks." } } },
			{ "ppr", new() { { "Deriv Stat Pickpocket Protection", "Level of defense against pickpocketing attempts." } } },
			{ "ltp", new() { { "Deriv Stat Loot Protection", "Protection level against theft or loss of loot." } } },
			{ "upr", new() { { "Deriv Stat Unconsciousness Protection", "Resistance to becoming unconscious." } } },
			{ "skpr", new() { { "Deriv Stat Stealth Kill Protection", "Protection from stealth kill attempts." } } },
			{ "kopr", new() { { "Deriv Stat Knockout Protection", "Resistance to being knocked out." } } },
			{ "cds", new() { { "Deriv Stat Cloth Dirtying Speed Km", "Speed at which clothing gets dirty during movement (per km)." } } },
			{ "edm", new() { { "Deriv Stat Equipment Use Damage Multiplier", "Multiplier for damage taken by equipment during use." } } },
			{ "prc", new() { { "Deriv Stat Picklock Return Chance", "Chance that a picklock returns after use." } } },
			{ "cdw", new() { { "Deriv Stat Clinch Damage To Weapon", "Amount of damage to weapons during clinch fights." } } },
			{ "eqw", new() { { "Deriv Stat Equipped Weight", "Total weight of currently equipped items." } } },
			{ "pla", new() { { "Deriv Stat Plating Ratio", "Ratio of plated armor coverage." } } },
			{ "wbc", new() { { "Deriv Stat Weapon Buff Charges", "Number of buff charges applied to weapons." } } },
			{ "cbi", new() { { "Deriv Stat Charisma From Buffed Items", "Charisma bonus provided by buffed items." } } },
			{ "nbi", new() { { "Deriv Stat Noise From Buffed Items", "Noise generated from buffed items affecting stealth." } } },
			{ "alc", new() { { "Deriv Stat Alcoholism", "Level of alcoholism affecting the character." } } },
			{ "map", new() { { "Deriv Stat Mean Attack Period", "Average time period between attacks." } } },
			{ "adm", new() { { "Deriv Stat Alcohol Digest Mod", "Modifier for the rate of alcohol digestion." } } },
			{ "alm", new() { { "Deriv Stat Alcohol Mood", "Mood influence caused by alcohol." } } },
			{ "hov", new() { { "Deriv Stat Hangover", "Severity or duration of hangover effects." } } },
			{ "btw", new() { { "Deriv Stat Boid Threat Weight", "Weight or influence of threats detected by AI boids." } } },
			{ "owl", new() { { "Deriv Stat Owl", "Unknown or specific stat related to 'Owl' (context needed)." } } },
			{ "rms", new() { { "Deriv Stat Real Move Speed Mod", "Modifier affecting the real movement speed of the character." } } },
			{ "deb", new() { { "Deriv Stat Debauchery", "Represents the character's tendency towards debauchery or immoral behavior." } } },
			{ "ach", new() { { "Deriv Stat Attack Charge", "Charge or buildup value before an attack." } } },
			{ "prs", new() { { "Deriv Stat Persuade", "Effectiveness of the character's persuasion attempts." } } },
			{ "imp", new() { { "Deriv Stat Impress", "Ability to impress or influence others." } } },
			{ "drd", new() { { "Deriv Stat Dread", "Level of fear or intimidation the character projects or feels." } } },
			{ "crc", new() { { "Deriv Stat Coerce", "Ability to coerce or force others to comply." } } },
			{ "dmt", new() { { "Deriv Stat Dominate", "Level of dominance exerted by the character." } } },
			{ "mgt", new() { { "Deriv Stat Might", "Measure of physical strength or power." } } },
			{ "bad", new() { { "Deriv Stat Badassness", "Degree of toughness or intimidating presence." } } },
			{ "nrv", new() { { "Deriv Stat Nervousness", "Level of nervousness or anxiety." } } },
			{ "vag", new() { { "Deriv Stat Violence Angriness", "Aggression level related to violent anger." } } },
			{ "mag", new() { { "Deriv Stat Material Angriness", "Angriness or frustration related to material issues." } } },
			{ "aag", new() { { "Deriv Stat Average Angriness", "General average of anger levels." } } },
			{ "red", new() { { "Deriv Stat Random Event Difficulty", "Difficulty modifier for random events." } } },
			{ "drv", new() { { "Deriv Stat Disabled Revive", "Indicates whether revival is disabled." } } },
			{ "pmc", new() { { "Deriv Stat Permanent Corpse", "Indicates if a corpse remains permanently." } } },
			{ "sdn", new() { { "Deriv Stat Service Denial", "Represents denial of services or interactions." } } },
			{ "brn", new() { { "Deriv Stat Brand", "Represents a brand or mark on the character." } } },
			{ "plr", new() { { "Deriv Stat Pillory", "Effect or status related to being in the pillory." } } },
			{ "bea", new() { { "Deriv Stat Beating", "Represents damage or punishment from beating." } } },
			{ "kko", new() { { "Deriv Stat Knock Out", "Chance or effect of knocking out an opponent." } } },
			{ "sse", new() { { "Deriv Stat Stealth Kill Strength Effect", "Modifier for strength effects during stealth kills." } } },
			{ "ies", new() { { "Deriv Stat Injury Effects Suppress", "Reduces or suppresses injury effects on the character." } } },
			{ "lrm", new() { { "Deriv Stat Lockpicking Recognizable Mod", "Modifier for how recognizable lockpicking attempts are." } } },
			{ "prm", new() { { "Deriv Stat Pickpocketing Recognizable Mod", "Modifier for how recognizable pickpocketing attempts are." } } },
			{ "uvh", new() { { "Deriv Stat Unawared Victim Hit Debuff", "Debuff applied when hitting an unaware victim." } } },
			{ "uva", new() { { "Deriv Stat Unawared Victim Attack Bonus", "Bonus damage or effect when attacking an unaware victim." } } },
			{ "cnp", new() { { "Deriv Stat Companion Nominal Price", "Base price value for a companion." } } },
			{ "cbp", new() { { "Deriv Stat Companion Buying Price", "Price to buy a companion." } } },
			{ "csp", new() { { "Deriv Stat Companion Selling Price", "Price gained from selling a companion." } } },
			{ "slp", new() { { "Deriv Stat Companion Legalization Price", "Cost to legalize a companion." } } },
			{ "cep", new() { { "Deriv Stat Companion Exchange Price", "Price related to companion exchanges." } } },
			{ "icp", new() { { "Deriv Stat Is Companion Available To Purchase", "Boolean or flag indicating if companion is available for purchase." } } },
			{ "crp", new() { { "Deriv Stat Craftsmanship Repair Price Mod", "Modifier reducing or increasing repair prices based on craftsmanship." } } },
			{ "dfe", new() { { "Deriv Stat Dog Found Event Prob", "Probability modifier for dog found events." } } },
			{ "csc", new() { { "Deriv Stat Combat Stamina Charged Regen", "Rate at which stamina regenerates when charged in combat." } } },
			{ "hvp", new() { { "Deriv Stat Has Visible Perks UI", "Flag indicating whether perks UI is visible." } } },
			{ "pqe", new() { { "Deriv Stat Pickpocketing Quick Escape", "Modifier for quick escape chance after pickpocketing." } } },
			{ "sks", new() { { "Deriv Stat Shop Keeper Shadiness", "Modifier affecting shopkeepers' trust or honesty." } } },
			{ "sst", new() { { "Deriv Stat Stolen Item Selling Thievery XP", "XP gain modifier from selling stolen items related to thievery skill." } } },
			{ "sss", new() { { "Deriv Stat Stolen Item Selling Stealth XP", "XP gain modifier from selling stolen items related to stealth skill." } } },
			{ "xst", new() { { "Deriv Stat Strength XP Gain Multiplier", "Multiplier for XP gain in strength skill." } } },
			{ "xag", new() { { "Deriv Stat Agility XP Gain Multiplier", "Multiplier for XP gain in agility skill." } } },
			{ "xvi", new() { { "Deriv Stat Vitality XP Gain Multiplier", "Multiplier for XP gain in vitality skill." } } },
			{ "xsp", new() { { "Deriv Stat Speech XP Gain Multiplier", "Multiplier for XP gain in speech skill." } } },
			{ "pxp", new() { { "Deriv Stat Prestige XP Gain Multiplier", "Multiplier for XP gain in prestige." } } },
			{ "xsw", new() { { "Deriv Stat Weapon Sword XP Gain Multiplier", "Multiplier for XP gain in sword weapon skill." } } },
			{ "xcr", new() { { "Deriv Stat Craftmanship XP Gain Multiplier", "Multiplier for XP gain in craftsmanship skill." } } },
			{ "xsu", new() { { "Deriv Stat Survival XP Gain Multiplier", "Multiplier for XP gain in survival skill." } } },
			{ "xhw", new() { { "Deriv Stat Heavy Weapon XP Gain Multiplier", "Multiplier for XP gain in heavy weapons skill." } } },
			{ "xma", new() { { "Deriv Stat Marksmanship XP Gain Multiplier", "Multiplier for XP gain in marksmanship skill." } } },
			{ "xsc", new() { { "Deriv Stat Scholarship XP Gain Multiplier", "Multiplier for XP gain in scholarship skill." } } },
			{ "srr", new() { { "Deriv Stat Stamina Hit Return Ratio", "Ratio affecting stamina returned upon hit." } } },
			{ "bap", new() { { "Deriv Stat Black Arts Apprentice Potion Quality Bonus", "Bonus to potion quality for black arts apprentices." } } },
			{ "alp", new() { { "Deriv Stat Alchemy Potion", "Effect or modifier related to alchemy potions." } } },
			{ "atd", new() { { "Deriv Stat Able To Dodge", "Indicates ability to dodge attacks." } } },
			{ "ams", new() { { "Deriv Stat Able To Master Strike", "Indicates ability to perform master strikes." } } },
			{ "rcx", new() { { "Deriv Stat Repair Price To Crafting XP", "XP gain modifier from repair price." } } },
			{ "lfb", new() { { "Deriv Stat Max Lockpicks From Blacksmithing", "Maximum lockpicks obtainable via blacksmithing." } } },
			{ "tba", new() { { "Deriv Stat Thunderous Blast Active", "Indicates whether thunderous blast is active." } } },
			{ "nrw", new() { { "Deriv Stat Perk No Rest For The Wicked Stamina Delta", "Stamina change for 'No Rest For The Wicked' perk." } } },
			{ "fac", new() { { "Deriv Stat Frisk Avoid Chance", "Chance to avoid frisking." } } },
			{ "ahe", new() { { "Deriv Stat Light Alcohol Healing Effect", "Healing effect from light alcohol." } } },
			{ "apo", new() { { "Deriv Stat Alcohol Positive Effects Offset", "Offset for positive alcohol effects." } } },
			{ "ano", new() { { "Deriv Stat Alcohol Negative Effects Offset", "Offset for negative alcohol effects." } } },
			{ "fpd", new() { { "Deriv Stat Forced Player Drunkenness", "Level of forced drunkenness on player." } } },
			{ "eph", new() { { "Deriv Stat Every Potion Healing Effect", "Healing effect of every potion." } } },
			{ "rpd", new() { { "Deriv Stat Reputation Propagation Distance Mod", "Modifier for how far reputation propagates." } } },
			{ "rpr", new() { { "Deriv Stat Reputation Propagation Relation Mod", "Modifier for reputation propagation based on relation." } } },
			{ "rpa", new() { { "Deriv Stat Reputation Propagation Ancestor Mod", "Modifier for reputation propagation through ancestors." } } },
			{ "hla", new() { { "Deriv Stat Heavy Light Armor", "Modifier or value related to heavy/light armor." } } },
			{ "rpp", new() { { "Deriv Stat Riposte Probability Penalty", "Penalty to riposte chance." } } },
			{ "efd", new() { { "Deriv Stat Enable Fall Damage", "Flag or modifier to enable or disable fall damage." } } },
			{ "aml", new() { { "Deriv Stat Alcoholism Minimum Level", "Minimum alcoholism level required for effects." } } },
			{ "bmr", new() { { "Deriv Stat Bushman RTPC", "RTPC related to bushman effect." } } },
			{ "lgp", new() { { "Deriv Stat Last Gasp Protection", "Protection effect for last gasp." } } },
			{ "bbn", new() { { "Deriv Stat Base Body Noise", "Base noise generated by the body." } } },
			{ "shd", new() { { "Deriv Stat Shoe Health Decrease Multiplier", "Multiplier for shoe health degradation." } } },
			{ "atp", new() { { "Deriv Stat Alco Teleport After Sleep Probability", "Probability to teleport after sleep under alcohol influence." } } },
			{ "hlm", new() { { "Deriv Stat Hunter Loot Amount Mod", "Modifier for loot amount from hunting." } } },
			{ "dip", new() { { "Deriv Stat Disabled Perfume", "Flag or modifier disabling perfume effects." } } },
			{ "shadiness", new() { { "Static Stat Shadiness", "Level of shadiness or suspiciousness of a character." } } },
			{ "combatLevel", new() { { "Static Stat Combat Level", "Character's combat skill level." } } },
			{ "initialDirtiness", new() { { "Static Stat Initial Dirtiness", "Starting level of dirtiness on character or item." } } }
		};

		public static string ToAttributeString(IEnumerable<BuffParam> parameters)
		{
			return string.Join(",", parameters.Select(p =>
			{
				if (!OperatorMap.TryGetValue(p.Operation, out var op))
					throw new InvalidOperationException($"Unsupported operation: {p.Operation}");

				return $"{p.Key}{op}{p.Value.ToString(CultureInfo.InvariantCulture)}";
			}));
		}

		public static IEnumerable<string> GetAllKeys()
		{
			return buffParamMap.Keys;
		}

		public static IEnumerable<string> GetAllNames()
		{
			return buffParamMap.Values
				.SelectMany(dict => dict.Keys);
		}

		public static IEnumerable<string> GetAllDescriptions()
		{
			return buffParamMap.Values
				.SelectMany(dict => dict.Values);
		}

		public static string GetName(string key)
		{
			return buffParamMap[key].Keys.FirstOrDefault() ?? $"Name to '{key}' not found";
		}

		public static string GetDescription(string key)
		{
			return buffParamMap[key].Values.FirstOrDefault() ?? $"Description to '{key}' not found";
		}
	}
}
